export const paths = {
  home: '/',
  about: '/about',
  projects: '/projects',
  services: '/services',
  epc: '/services/epc',
  wellTesting: '/services/well-testing',
  installationCommissioning: '/services/installation-commissioning',
  engineeringDesign: '/services/engineering-design',
  productionImprovement: '/services/production-improvement',
  productionFacilities: '/services/production-facilities',
  wellheadMaintenance: '/services/wellhead-maintenance',
  operationsMaintenance: '/services/operations-maintenance',
  shutinWellReentry: '/services/shut-in-well-re-entry',
  equipmentSupply: '/services/equipment-supply',
  equipmentRepairs: '/services/equipment-repairs',
  equipmentRentals: '/services/equipment-rentals',
  producedWaterManagement: '/services/produced-water-management',
  sandManagement: '/services/sand-management',
  portfolio: '/portfolio',
  csr: '/csr',
  hseq: '/hseq',
  contact: '/contact',
  privacy: '/privacy-policy',
  blog: '/blog',
};
