export const paths = {
  home: '/',
  about: '/about',
  managementTeam: '/management-team',
  projects: '/projects',
  services: '/services',
  epc: '/services/epc',
  wellTesting: '/services/well-testing',
  installationCommissioning: '/services/installation-commissioning',
  engineeringDesign: '/services/engineering-design',
  productionImprovement: '/services/production-improvement',
  productionFacilities: '/services/production-facilities',
  wellheadMaintenance: '/services/wellhead-maintenance',
  operationsMaintenance: '/services/operations-maintenance',
  shutinWellReentry: '/services/shut-in-well-re-entry',
  equipmentSupply: '/services/equipment-supply',
  equipmentRepairs: '/services/equipment-repairs',
  equipmentRentals: '/services/equipment-rentals',
  producedWaterManagement: '/services/produced-water-management',
  sandManagement: '/services/sand-management',
  portfolio: '/portfolio',
  oilAndGas: '/portfolio/oil-and-gas',
  csr: '/csr',
  hseq: '/hseq',
  contact: '/contact',
  privacy: '/privacy-policy',
  blog: '/blog',
  blogPost: (slug: string) => `/blog/${slug}`,
};

export const adminPaths = {
  login: '/admin/login',
  dashboard: '/admin',
  blog: '/admin/blog',
  blogNew: '/admin/blog/new',
  blogEdit: (id: string) => `/admin/blog/${id}/edit`,
};
